# Generated by Django 5.1.6 on 2026-03-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('gfg', 'GeeksForGeeks'), ('codeforces', 'Codeforces'), ('codechef', 'CodeChef'), ('hackerrank', 'HackerRank'), ('other', 'Other')], default='leetcode', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('unsolved', 'Unsolved'), ('solved', 'Solved'), ('revision', 'Needs Revision')], default='unsolved', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_on', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='problems.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brute_force', models.TextField(blank=True)),
                ('optimized', models.TextField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=50)),
                ('space_complexity', models.CharField(blank=True, max_length=50)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='problems.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.topic'),
        ),
    ]
