# Generated by Django 5.1.6 on 2026-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_topic_problem_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_solved_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Stats',
            },
        ),
    ]
