# Generated by Django 5.1.6 on 2026-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='problem',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
