# Generated by Django 5.1.6 on 2026-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_ease_factor_problem_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(default='python', max_length=30),
        ),
    ]
