# Generated by Django 5.1.6 on 2026-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_solution_code_solution_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_spent_mins',
            field=models.IntegerField(default=0),
        ),
    ]
