# Generated by Django 5.1.6 on 2026-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_time_spent_mins'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_username', models.CharField(blank=True, max_length=100)),
                ('gfg_username', models.CharField(blank=True, max_length=100)),
                ('codeforces_username', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
